//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consoleapp_estudos_net_core_rabbitmq.v1.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("consoleapp_estudos_net_core_rabbitmq.v1.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar a instância da aplicação no Event Viewer: {0}.
        /// </summary>
        internal static string ERRO_CONFIGURACAO_EVENT_VIEWER {
            get {
                return ResourceManager.GetString("ERRO_CONFIGURACAO_EVENT_VIEWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRO na execução do programa: {0}.
        /// </summary>
        internal static string ERRO_EXECUCAO_PROGRAMA {
            get {
                return ResourceManager.GetString("ERRO_EXECUCAO_PROGRAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INÍCIO da execução do programa..
        /// </summary>
        internal static string INICIO_EXECUCAO_PROGRAMA {
            get {
                return ResourceManager.GetString("INICIO_EXECUCAO_PROGRAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem recuperada: {0}.
        /// </summary>
        internal static string MENSAGEM_RECUPERADA {
            get {
                return ResourceManager.GetString("MENSAGEM_RECUPERADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressione qualquer tecla para sair....
        /// </summary>
        internal static string PRESSIONE_QUALQUER_TECLA_SAIR {
            get {
                return ResourceManager.GetString("PRESSIONE_QUALQUER_TECLA_SAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo de execução total do programa: {0}.
        /// </summary>
        internal static string TEMPO_EXECUCAO_TOTAL {
            get {
                return ResourceManager.GetString("TEMPO_EXECUCAO_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÉRMINO da execução do programa..
        /// </summary>
        internal static string TERMINO_EXECUCAO_PROGRAMA {
            get {
                return ResourceManager.GetString("TERMINO_EXECUCAO_PROGRAMA", resourceCulture);
            }
        }
    }
}
